name: Build and deploy Node.js + Angular app to Azure Web App - pika-trading-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          cd pika-trading-backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd pika-trading-frontend
          npm install

      - name: Install Angular CLI
        run: |
          cd pika-trading-frontend
          npm install @angular/cli

      - name: Build Angular frontend
        run: |
          cd pika-trading-frontend
          npx ng build --configuration production


      - name: Move frontend build to backend
        run: |
          mkdir -p pika-trading-backend/dist/pika-trading-frontend/browser
          cp -r pika-trading-frontend/dist/pika-trading-frontend/browser/* pika-trading-backend/dist/pika-trading-frontend/browser/

      - name: Zip artifact for deployment
        run: |
          cd pika-trading-backend
          zip -r release.zip server.js package.json package-lock.json dist/ data/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-angular-app
          path: pika-trading-backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-angular-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F885B893B2294667A7F7F7736151E97A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CD426CC5F610471F8DCA0BC46AFABAE4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAD76A6331AD488FAF52073FF0889BEC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pika-trading-app'
          slot-name: 'Production'
          package: .
